### PR TITLE
Fix spectator behaviour on section transition

### LINKED ISSUE #54: Teleport spectating players with player on sectiontransition
Right now it wont teleport the person in spectator mode, just have them freak out and be stuck.

### PR DESCRIPTION
**Pull request by Norazan**
Closes #54

### CODE REVIEW

File: src/main/java/com/derongan/minecraft/deeperworld/extensions/DeeperWorldExtensions.kt [hunk 1]
```diff
@@ -31,4 +32,21 @@ internal fun Player.getLeashedEntities(): List<LivingEntity> {
     return getNearbyEntities(20.0, 20.0, 20.0)
         .filterIsInstance<LivingEntity>()
         .filter { it.isLeashed && it.leashHolder == this }
+}
+
+internal fun Player.teleportWithSpectator(loc : Location){
+    val nearbyPlayers = getNearbyEntities(5.0, 5.0, 5.0).filterIsInstance<Player>()
+
+    var spectator : Player? = null
```
Comment (0ffz) [inline src/main/java/com/derongan/minecraft/deeperworld/extensions/DeeperWorldExtensions.kt:40]: Since multiple people can be spectators of the same player, I think we should just filter the list of nearby players and run a forEach on them.

When selecting just one, I'd prefer `nearbyPlayers.first { it.spectatorTarget == this }`

**Review by 0ffz — CHANGES_REQUESTED** [review]

**Review by 0ffz — APPROVED** [review]
