### PR TITLE
Update, fix and add more sync stuff

### LINKED ISSUE #26: Replace outdated permission check on deeperworld.changesection to deeperworld.admin
https://github.com/MineInAbyss/DeeperWorld/blob/56382626bf4320418e47ea1c84681cdf96dcd662/src/main/java/com/derongan/minecraft/deeperworld/Permissions.java

### PR DESCRIPTION
**Pull request by Boy0000**
StructureGrowEvent is called for trees etc, which was not synced before
BlockGrowEvent seems fine, not sure why it would lag buch but
BlockGrowEvent isnt called for bonemeal so manual interaction check

Fixes pistons, from my testing atleast. Calls the event in above section seems to fix
Calls event for pistons breaking stuff, clear drops for no dupes
This event should also be called if water breaks say crops in a transition

Tested with PhysicsEvent for rails and stuff and it seems to have improved since 1.16 or whenever we disabled it
Even when "cancelled" it triggered redstone so not much use in it

Updates some sign stuff to component cuz paper
Shulkers should have the same properties as chests, tho ill need to test this more (had similar issues with blocky so)<

Closes #26

### CODE REVIEW

File: src/main/kotlin/com/mineinabyss/deeperworld/synchronization/SectionSyncListener.kt [hunk 1]
```diff
@@ -179,18 +177,21 @@ object SectionSyncListener : Listener {
...
-            entity.location.getNearbyPlayers(5.0).forEach {
-                it.error("Spawning of $entityType is disabled in section overlaps.")
-            }
+            (entityType == EntityType.WITHER || entityType == EntityType.IRON_GOLEM)
+        ) {
+            entity.world.getNearbyEntitiesByType(
+                entityType.entityClass,
+                entity.location.correspondingLocation ?: return,
+                1.0
+            ).firstOrNull()?.remove() ?: return
```
Comment (DevScyu) [inline src/main/kotlin/com/mineinabyss/deeperworld/synchronization/SectionSyncListener.kt:193]: Should this be a remove ? Since i thought the logic was the event gets fired, checks if it was cancelled, then if it wasn't then it would spawn, this check would be before that check no?

File: src/main/kotlin/com/mineinabyss/deeperworld/synchronization/ExploitPreventionListener.kt [hunk 2]
```diff
@@ -1,24 +1,45 @@
...
 
-    /** Disables pistons retracting if they are in the overlap of two sections */
     @EventHandler
-    fun onPistonRetractEvent(event: BlockPistonRetractEvent) {
-        if (event.blocks.any { it.location.correspondingSection != null })
-            event.isCancelled = true
+    fun BlockBreakBlockEvent.onPistonBreakBlock() {
+        val corrBlock = block.location.correspondingLocation?.block ?: return
+        val corrSource = source.location.correspondingLocation?.block ?: return
+        BlockBreakBlockEvent(corrBlock, corrSource, emptyList<ItemStack>()) // Empty drops to avoid dupes
```
Comment (DevScyu) [inline src/main/kotlin/com/mineinabyss/deeperworld/synchronization/ExploitPreventionListener.kt:43]: You are not calling this event like above.

Also i do not think events work like this, you would manually need to trigger a block break if i remember correctly. The event is only to trigger listeners.

File: src/main/kotlin/com/mineinabyss/deeperworld/synchronization/SectionSyncListener.kt (hunk 1 above)
Comment (Boy0000) [reply src/main/kotlin/com/mineinabyss/deeperworld/synchronization/SectionSyncListener.kt:193]: Previously it just cancelled the event, but made it so that the synced entity is removed and not duped

File: src/main/kotlin/com/mineinabyss/deeperworld/synchronization/ExploitPreventionListener.kt (hunk 2 above)
Comment (Boy0000) [reply src/main/kotlin/com/mineinabyss/deeperworld/synchronization/ExploitPreventionListener.kt:43]: Yeah i think it just worked and didnt look over, would manually removing the block make more sense? just set it to air
should make more sense aswell?
